---
- name: "Set fact helm file"
  ansible.builtin.set_fact:
    my_helmfile: "{{ my_workdir }}/ibm-seas-{{ compatibility_matrix[seas_version].helm_version }}.tgz"
    my_valuesfile: "{{ my_workdir }}/myseas_values-{{ my_serial }}.yml"

- name: Generate my_values.yml
  ansible.builtin.template:
    src: "values.yml.j2"
    dest: "{{ my_valuesfile }}"
    mode: "0640"

- name: Debug
  ansible.builtin.debug:
    msg:
      - "Image Tag         ................. {{ compatibility_matrix[seas_version].image_tag }}"
      - "helm install --timeout {{ seas_helm_timeout }} -f {{ my_valuesfile }} -n {{ seas_namespace }} {{ seas_helm_release }} {{ my_helmfile }}"

- name: Run Helm install command
  ansible.builtin.command:
    cmd: "helm install --timeout {{ seas_helm_timeout }} -f {{ my_valuesfile }} -n {{ seas_namespace }} {{ seas_helm_release }} {{ my_helmfile }}"
  register: helm_cout
  changed_when: helm_cout.rc != 0

- name: "Lookup SEAS Pod"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ seas_namespace }}"
    label_selectors:
      - release={{ seas_helm_release }}
    wait: true
    wait_sleep: 30
    wait_timeout: 300 # 5 mins until we give up waiting for the pod to get into the expected state
    wait_condition:
      type: Ready
      status: "True"
  register: seas_pod

- name: Configure facts
  ansible.builtin.set_fact:
    seas_pod_name: "{{ seas_pod.resources[0].metadata.name }}"

- name: "IBM Sterling SEAS Summary:"
  ansible.builtin.debug:
    msg:
      - "IBM Sterling SEAS status ............................ Ready!"
      - "SEAS namespace ...................................... {{ seas_namespace }}"
      - "Pod name ............................................ {{ seas_pod_name }}"
      - "For username and password check secret .............. {{ seas_secret }}'"
