---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sterling-seas-config
  labels:
    app.kubernetes.io/name: sterling-seas
    app.kubernetes.io/component: configuration
data:
  SEAS_NAMESPACE: "sterling-seas-dev01"
  #
  # # Sterling External Authentication Server Configuration
  # # -----------------------------------------------------------------------------
  # 
  # # SEAS Action (install or upgrade)
  # SEAS_ACTION: "install"
  # 
  # # SEAS Instance Configuration
  # SEAS_NAMESPACE: "sterling-seas01"
  # SEAS_VERSION: "1.6.1.0"
  # SEAS_LICENSE_TYPE: "non-prod"
  # 
  # # Storage Configuration
  # STORAGE_CLASS_RWX: ""
  # STORAGE_CLASS_RWO: ""
  # SEAS_PVC_STORAGE_SIZE: "1Gi"
  # 
  # # Additional Settings
  # SEAS_SYS_PASSPHRASE: "Password123!"
  # SEAS_ADMIN_PASSWORD: "Password123!"
  # SEAS_KEYSTORE_PASSPHRASE: "Change1t@"
  # SEAS_TRUSTSTOREPASSWORD: "Change1t@"
  # 
  # # Helm Configuration
  # SEAS_SKIP_HELM: "false"
  # 
  # # Additional Configuration
  # # Note: Sensitive values like passwords should be stored in Secrets
  # # See secret-template.yaml for sensitive configuration


