---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sterling-b2bi-config
  labels:
    app.kubernetes.io/name: sterling-b2bi
    app.kubernetes.io/component: configuration
data:
  SI_INSTANCEID: "dev01"
  SI_VERSION: "6.2.2.0"
  #
  # # Sterling B2B Integrator Configuration
  # # -----------------------------------------------------------------------------
  # # B2Bi Action (install or upgrade)
  # SI_ACTION: "install" 
  # 
  # # B2Bi Instance Configuration
  # SI_INSTANCEID: "dev01"
  # SI_VERSION: "6.2.2.0"
  # #SI_LICENSETYPE: "prod"
  # 
  # # Storage Configuration
  # STORAGE_CLASS_RWX: ""
  # STORAGE_CLASS_RWO: ""
  # B2BI_STORAGE_CAPACITY: "10Gi"
  # 
  # # Database Configuration
  # SI_DBVENDOR: "db2"
  # SI_DBHOST: ""
  # SI_DBPORT: "50000"
  # SI_DBNAME: "B2BIDB"
  # SI_DBUSER: "db2inst1"
  # SI_ORACLESERVICENAME: false
  # 
  # # Additional Settings
  # SI_SYSTEM_PASSPHRASE: "passw0rd"
  # SI_ENV_TIMEZONE: "UTC"
  # SI_ROUTEDOMAIN: "company.com"
  # SI_ADMIN_MAILADDR: "admin@company.com"
  # SI_ADMIN_SMTPHOST: "smtp.company.com"
  # 
  # # Helm Configuration
  # SI_SKIP_HELM: "false"
  