---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sterling-cdws-config
  labels:
    app.kubernetes.io/name: sterling-cdws
    app.kubernetes.io/component: configuration
data:
  CDWS_NAMESPACE: "sterling-cdws-dev01"
  #
  # # Connect:Direct WebService Configuration
  # # -----------------------------------------------------------------------------
  # # CDWS Action (install or upgrade)
  # CDWS_ACTION: "install"
  # 
  # # CDWS Instance Configuration
  # CDWS_NAMESPACE: "sterling-cdws01"
  # CDWS_VERSION: "6.4.0.4_ifix001"
  # CDWS_LICENSE_TYPE: "non-prod"
  # 
  # # Storage Configuration
  # STORAGE_CLASS_RWX: ""
  # STORAGE_CLASS_RWO: ""
  # CDWS_STORAGE_CAPACITY: "500Mi"
  # 
  # # Resource Limits and Requests
  # CDWS_CPU_LIMITS: "3000m"
  # CDWS_MEM_LIMITS: "2Gi"
  # CDWS_CPU_REQUESTS: "1500m"
  # CDWS_MEM_REQUESTS: "1Gi"
  # 
  # # Helm Configuration
  # CDWS_SKIP_HELM: "false"
  # 
  # # Additional Configuration
  # # Note: Sensitive values like passwords and keystores should be stored in Secrets
  # # See secret-template.yaml for sensitive configuration
