---
- name: Define multiple variables
  ansible.builtin.set_fact:
    cd_cert_crt: "{{ my_workdir }}/cdcert.crt"  # CD install script only support extensions .crt, .pem and .cer
    cd_cert_key: "{{ my_workdir }}/cdkey.pem"
    cd_cert_pem: "{{ my_workdir }}/cdcert.pem"

# Create Certificate for Connect:Direct on Kubernetes
# -----------------------------------------------------------------------------
- name: Running OpenSSL command
  ansible.builtin.command:
    cmd: "openssl req -x509 -sha512 -days 3650 -newkey rsa:2048 -new -nodes -keyout {{ cd_cert_key }} -out {{ cd_cert_crt }} -subj '/CN={{ cd_nodename }}'"
  register: cout
  changed_when: false

- name: Concat C:D certificates
  ansible.builtin.shell:
    cmd: "cat {{ cd_cert_key }} {{ cd_cert_crt }} > {{ cd_cert_pem }}"
  changed_when: false
  when: cout.rc == 0

# Create Certificate for Connect:Direct on Kubernetes
# CD install script only support extensions .crt, .pem and .cer
# -----------------------------------------------------------------------------
- name: Create or update Kubernetes secret with certificates files
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ cd_deploy_cert_secret }}"
        namespace: "{{ cd_namespace }}"
      data:
        cdcert.pem: "{{ lookup('file', cd_cert_pem) | b64encode }}"
