---
galaxy_info:
  author: Enio Basso
  description: Install IBM Operator Catalog for OpenShift/Kubernetes
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - ibm
    - operator
    - catalog
    - olm
    - openshift
    - kubernetes

dependencies: []

# Made with Bob
