- name: Deploy IBM Sterling Transformation Extender Advanced
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: itxa_deploy_db2
      when: itxa_deploy_db2_enabled | default(true) | bool

    - role: itxa_setup_db2
      when: itxa_setup_db2_enabled | default(true) | bool

    - role: itxa_deploy
      when: itxa_deploy_enabled | default(true) | bool